### ISSUE TITLE
can't detect pk in some DBMS

### ISSUE THREAD

**Issue by deffence1776** [joel-costigliola/assertj-db#31]
In some DBMS, DatabaseMetaData#getPrimaryKeys returns COLUMN_NAME in lowercase. 
(I tried sqlite3)

I think you should add String#toUpperCase when you get primarykey's column name at org.assertj.db.type.Table#collectPrimaryKeyName

```java
     while (resultSet.next()) {
        String columnName = resultSet.getString("COLUMN_NAME").toUpperCase();
        if (getColumnsNameList().indexOf(columnName) != -1) {
          pksNameList.add(columnName);
        }
      }
```

Thank you.

**Comment by tnazare** [comment]
#33

**Comment by regis1512** [comment]
Sorry to have be long to implement a solution.
You can now find new classes : LetterCase and all associated classes (especially SourceWithLetterCase and DataSourceWithLetterCase) which are here to fix this problem.

When you instantiate a SourceWithLetterCase or DataSourceWithLetterCase, you can indicate the behavior (the conversion like upper and lower and the comparison) with the letter case of the tables, columns and primary keys.
I hope that with this flexibility that all the users can find a compatible solution with their database.
Please note that the solution is extensible because LetterCase use CaseComparison and CaseConversion which are interfaces.

**Comment by regis1512** [comment]
And thank to tnazare for his proposition
