### ISSUE TITLE
Disable toUpperCase on table name

### ISSUE THREAD

**Issue by glefloch** [joel-costigliola/assertj-db#32]
Hi, 

When I try to use asserJ-db, all query to database use uppercase table nam,w hich is actually not working with our curretn Mysql configuration. 
I know I can allow it in the my.cnf configuration file. But on some environment this is impossible. 
I that possible to a setter to disable it? 

Regards

**Comment by tnazare** [comment]
Hi,

I have the same problem...
Any news on this issue?

Thib.

**Comment by glefloch** [comment]
Unfortunately no...

**Comment by tnazare** [comment]
#33

**Comment by regis1512** [comment]
Sorry to have be long to implement a solution.
You can now find new classes : LetterCase and all associated classes (especially SourceWithLetterCase and DataSourceWithLetterCase) which are here to fix this problem.

When you instantiate a SourceWithLetterCase or DataSourceWithLetterCase, you can indicate the behavior (the conversion like upper and lower and the comparison) with the letter case of the tables, columns and primary keys.
I hope that with this flexibility that all the users can find a compatible solution with their database.
Please note that the solution is extensible because LetterCase use CaseComparison and CaseConversion which are interfaces.

**Comment by regis1512** [comment]
And thank to tnazare for his proposition
